name: DevSecOps Pipeline

on: [push]

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Lint YAML
        run: |
          pip install yamllint
          yamllint -d "{extends: relaxed, ignore: [.github/, k8s/]}" .

      - name: Build Docker image
        run: docker build -t flask-app .

      - name: Scan filesystem (Trivy)
        uses: aquasecurity/trivy-action@0.20.0
        with:
          scan-type: "fs"
          scan-ref: "."

      - name: Scan Docker image
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: "flask-app"

      - name: Install Conftest
        run: |
          curl -L https://github.com/open-policy-agent/conftest/releases/download/v0.45.0/conftest_0.45.0_Linux_x86_64.tar.gz -o conftest.tar.gz
          tar -xzf conftest.tar.gz
          sudo mv conftest /usr/local/bin

      - name: Run Conftest
        run: conftest test k8s/deployment.yaml --policy policy/